version: '3.9'
services:
  users:
    image: users:latest
    environment:
      - RUN_MODE=DEV
      - PORT=12345
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/
    volumes:
      - ./app:/code/app
      - ./tests:/code/test
    ports:
      - "12345:12345"
    command: uvicorn app.main:app --host=0.0.0.0 --port=12345 --reload

    restart: on-failure
    networks:
      - eventito-dev-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - eventito-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  eventito-dev-network:
    name: eventito-dev-network
    external: true
